// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerManagement.Data;

#nullable disable

namespace ServerManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728153141_yun")]
    partial class yun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerManagement.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerId");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            City = "Nashville",
                            IsOnline = true,
                            Name = "Server 1"
                        },
                        new
                        {
                            ServerId = 2,
                            City = "Nashville",
                            IsOnline = false,
                            Name = "Server 2"
                        },
                        new
                        {
                            ServerId = 3,
                            City = "Nashville",
                            IsOnline = false,
                            Name = "Server 3"
                        },
                        new
                        {
                            ServerId = 4,
                            City = "Nashville",
                            IsOnline = true,
                            Name = "Server 4"
                        },
                        new
                        {
                            ServerId = 5,
                            City = "Nolensville",
                            IsOnline = true,
                            Name = "Server 5"
                        },
                        new
                        {
                            ServerId = 6,
                            City = "Nolensville",
                            IsOnline = false,
                            Name = "Server 6"
                        },
                        new
                        {
                            ServerId = 7,
                            City = "Nolensville",
                            IsOnline = true,
                            Name = "Server 7"
                        },
                        new
                        {
                            ServerId = 8,
                            City = "Franklin",
                            IsOnline = true,
                            Name = "Server 8"
                        },
                        new
                        {
                            ServerId = 9,
                            City = "Franklin",
                            IsOnline = false,
                            Name = "Server 9"
                        },
                        new
                        {
                            ServerId = 10,
                            City = "Franklin",
                            IsOnline = false,
                            Name = "Server 10"
                        },
                        new
                        {
                            ServerId = 11,
                            City = "Franklin",
                            IsOnline = true,
                            Name = "Server 11"
                        },
                        new
                        {
                            ServerId = 12,
                            City = "Knoxville",
                            IsOnline = false,
                            Name = "Server 12"
                        },
                        new
                        {
                            ServerId = 13,
                            City = "Knoxville",
                            IsOnline = true,
                            Name = "Server 13"
                        },
                        new
                        {
                            ServerId = 14,
                            City = "Knoxville",
                            IsOnline = false,
                            Name = "Server 14"
                        },
                        new
                        {
                            ServerId = 15,
                            City = "Knoxville",
                            IsOnline = true,
                            Name = "Server 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
